![](https://i.imgur.com/0AUxkXt.png)

# Assignment 1 - The Hacker Rank

HackerRank is a place where programmers from all over the world come together to solve problems in a wide range of Computer Science domains.

As you solve more challenges, you earn points and move up the HackerRank Leaderboard.

Looking for a job at an awesome company? You can get hired by solving [challenges](https://www.hackerrank.com/jobs/search)!

It's cool. Let's establish your knowledge and fight for glory!

But before that let's make it clear that..

## Note-taking is IMPORTANT

Blog: [Why is note-taking important](https://nickblackbourn.com/blog/why-is-note-taking-important/)

Note taking isn’t just important for college students, it’s a valuable life skill.

Effective note taking helps you to remember information and aids your understanding of that information. 

**Notes boost your understanding**

By making notes, you force yourself to construct a conceptual mental representation of the ideas you are grappling with. It is this process that helps you comprehend the subject matter you are working with.

**Notes are a repository of your thinking**

When you need to recall something that you came across a while ago, you can go over the main ideas by looking over your notes. This is why good, comprehensive notes are so useful; they are a catalogue of the best ideas you’ve encountered, and what you thought about them.

etc.









## Requirements

Pick 10 challenges on HackerRank about SQL and 5 about Python in **easy** level:

[HackerRank - Domain SQL](https://www.hackerrank.com/domains/sql?filters%5Bdifficulty%5D%5B%5D=easy&filters%5Bsubdomains%5D%5B%5D=select)

[HackerRank - Domain Python](https://www.hackerrank.com/domains/python?filters%5Bdifficulty%5D%5B%5D=easy)

For each challenge:

* Create a markdown cell first that describes the challenge.
* Solve the challenge on HackerRank and copy your solution to a code cell below
* (Optional) A short description about how you came up with the solution would be awesome.

## Example

### SQL


#### Problem 1

Query all columns for all American cities in **CITY** with populations larger than 100000. The CountryCode for America is USA.

**Input Format**

The **CITY** table is described as follows:

| Field | Type |
|:----:|:---:|
| ID | NUMBER |
| NAME | VARCHAR2(17) |
| COUNTRYCODE | VARCHAR2(3) |
| DISTRICT | VARCHAR2(20) |
| POPULATION | NUMBER |

In [0]:
# Solution
# SELECT * from city WHERE population>100000 AND countrycode='USA';

### Python

#### Problem 1

**Task** 
Given an integer, , perform the following conditional actions:

* If `n` is odd, print *Weird*
* If `n` is even and in the inclusive range of 2 to 5, print *Not Weird*
* If `n` is even and in the inclusive range of 6 to 20, print *Weird*
* If `n` is even and greater than 20, print *Not Weird*

**Input Format**

A single line containing a positive integer, .

**Output Format**

Print Weird if the number is weird; otherwise, print Not Weird.

In [0]:
n = int(input())

if n % 2 == 1:
    print('Weird')
else:
    if (n >= 2) and (n <= 5):
        print('Not Weird')
    elif (n >= 6) and (n <= 20):
        print('Weird')
    else:
        print('Not Weird')

## Your turn

Good luck and have fun!

## PYTHON


### Problem 1: collections.Counter()

#### Task 

***Raghu*** is a shoe shop owner. His shop has  $X$ number of shoes. 
He has a list containing the size of each shoe he has in his shop. 
There are $N$  number of customers who are willing to pay $x_i$  amount of money only if they get the shoe of their desired size.

Your task is to compute how much money ***Raghu*** earned.

#### Input format

The first line contains $X$, the number of shoes. <br/>
The second line contains the space separated list of all the shoe sizes in the shop. <br/>
The third line contains $N$ , the number of customers. <br/>
The next  $N$ lines contain the space separated values of the ***shoe size***  desired by the customer and $x_i$ , the price of the shoe.

#### Output format

Print the amount of money earned by ***Raghu***.

In [0]:
#import high-perfromance container datatypes
from collections import Counter

def main():
    n = int(input())
    cnt = Counter(map(int,input().split()))
    
    RaghuEarn = 0
    
    for _ in range(int(input())):
        s, p = list(map(int, input().split()))
        RaghuEarn += min(1, cnt[s]) * p
        cnt[s] = max(0, cnt[s] - 1)
    
    print(RaghuEarn)
    


if __name__ == '__main__':
    main()

10
2 3 4 5 6 8 7 6 5 18
6
6 55
6 45
6 55 
4 40 
18 60
10 50
200


### Problem 2:  DefaultDict Tutorial

#### Task

In this challenge, you will be given $2$ integers, $n$ and $m$. There are $n$ words, which might repeat, in word group $A$. There are $m$ words belonging to word group $B$. For each  $m$ words, check whether the word has appeared in group $A$ or not. Print the indices of each occurrence of $m$ in group $A$ . If it does not appear, print $-1$.

#### Input format

The first line contains integers, $n$ and $m$ separated by a space. <br/>
The next $n$ lines contains the words belonging to group $A$. <br/>
The next $m$ lines contains the words belonging to group $B$. <br/>

#### Output format

Output $m$ lines

The $i^{th}$  line should contain the $1$-indexed positions of the occurrences of the $i^{th}$ word separated by spaces.

In [0]:
from collections import defaultdict 

def main():
    d = defaultdict(list)
    n, m = list(map(int, input().split()))
    for i in range(1, n + 1):
        w = input()
        d[w].append(i) #add index of w's appearance in group A
    
    for _ in range(m):
        w = input()
        if d[w]:
            print(*d[w]) # print out all indexes of group B's word appearing in group A 
        else:
            print(-1)
if __name__ == '__main__':
    main()

5 2
a
a
b
a
b
a
1 2 4
b
3 5


### Problem 3: itertools.product()

#### Task

You are given a two lists  $A$ and $B$ . Your task is to compute their cartesian product $AXB$

#### Input format

The first line contains the space separated elements of list $A$ . <br/>
The second line contains the space separated elements of list $B$.

Both lists have no duplicate integer elements.

#### Output format

Output the space separated tuples of the cartesian product.

In [1]:
import itertools

def main():
    A = list(map(int, input().split()))
    B = list(map(int, input().split()))
    
    print(*itertools.product(A,B))


if __name__ == '__main__':
    main()

1 2
3 4
(1, 3) (1, 4) (2, 3) (2, 4)


### Problem 4: Map and Lambda Function

#### Task

You have to generate a list of the first $N$ fibonacci numbers, $0$ being the first number. Then, apply the map function and a lambda expression to cube each fibonacci number and print the list.

#### Input format

One line of input: an integer $N$ .

#### Output format

A list on a single line containing the cubes of the first $N$ fibonacci numbers.

In [2]:
cube = lambda x: x ** 3 # complete the lambda function 

def fibonacci(n):
    res = [0,1]
    for i in range(2,n):
        res.append(res[i-1] + res[i - 2])
    # return a list of fibonacci numbers
    return res[:n]

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

5
[0, 1, 1, 8, 27]


### Problem 5: Eye and Identity

#### Task
Your task is to print an array of size $N$X$M$ with its main diagonal elements as $1$'s and $0$'s everywhere else.

#### Input format
A single line containing the space separated values of $N$ and $M$. <br/> 
$N$  denotes the rows. <br/>
$M$ denotes the columns.

#### Output format

Print the desired $N$ X $M$ array.

In [3]:
import numpy as np

def main():
    N,M = list(map(int, input().split()))
    print(np.eye(N,M))

if __name__ == '__main__':
    np.set_printoptions(sign=' ')
    main()



3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## SQL

### Problem 1:  Employee names

Write a query that prints a list of employee names (i.e.: the name attribute) from the **Employee** table in alphabetical order.

#### Input format

The **Employee** table containing employee data for a company is described as follows:

| Column | Type |
|:----:|:---:|
| employee_id| Integer |
| name | String |
| months | Integer |
| salary | Integer |

where employee_id is an employee's ID number, name is their name, months is the total number of months they've been working for the company, and salary is their monthly salary.

In [0]:
# solution
# SELECT name FROM Employee ORDER BY name;

### Problem 2: Employee Salaries

Write a query that prints a list of employee names (i.e.: the name attribute) for employees in Employee having a salary greater than $\$2000$  per month who have been employees for less than $10$ months. Sort your result by ascending employee_id.

#### Input format

The **Employee** table containing employee data for a company is described as follows:

| Column | Type |
|:----:|:---:|
| employee_id| Integer |
| name | String |
| months | Integer |
| salary | Integer |

where employee_id is an employee's ID number, name is their name, months is the total number of months they've been working for the company, and salary is their monthly salary.

In [0]:
# solution
# SELECT name FROM Employee WHERE months < 10 AND salary > 2000 ORDER BY employee_id;

#### Problem 3: Higher Than 75 Marks

Query the Name of any student in **STUDENTS** who scored higher than $75$ Marks. Order your output by the last three characters of each name. If two or more students both have names ending in the same last three characters (i.e.: Bobby, Robby, etc.), secondary sort them by ascending ID.

### Input format
The **STUDENTS** table is described as follows: 

| Column | Type |
| -- | -- |
| ID | Integer |
| Name | String |
| Marks | Integer |

The Name column only contains uppercase (A-Z) and lowercase (a-z) letters.

In [0]:
# solution
# SELECT Name from STUDENTS where Marks > 75 ORDER BY right(Name, 3) , ID;

### Problem 4:  Weather Observation Station 8

Query the list of CITY names from **STATION** which have vowels (i.e., a, e, i, o, and u) as both their first and last characters. Your result cannot contain duplicates.

#### Input format

The **STATION** table is described as follows:

| Field | Type |
|:----:|:----:|
| ID | NUMBER |
| CITY | VARCHAR2(21) |
| STATE | VARCHAR2(2)|
| LAT_N | NUMBER |
| LONG_W | NUMBER |

where LAT_N is the northern latitude and LONG_W is the western longitude.

In [0]:
# Solution
# SELECT distinct CITY FROM STATION WHERE LEFT(CITY,1) in ('a', 'o', 'e', 'u', 'i' )
#                                    AND RIGHT(CITY,1) in ('a', 'o', 'e', 'u', 'i');

### Problem 5:  Weather Observation Station 9

Query the list of CITY names from **STATION** that do not start with vowels. Your result cannot contain duplicates.

#### Input format

The **STATION** table is described as follows:

| Field | Type |
|:----:|:----:|
| ID | NUMBER |
| CITY | VARCHAR2(21) |
| STATE | VARCHAR2(2)|
| LAT_N | NUMBER |
| LONG_W | NUMBER |

where LAT_N is the northern latitude and LONG_W is the western longitude.

In [0]:
# Solution
# SELECT distinct CITY FROM STATION WHERE LEFT(CITY,1) not in ('a', 'o', 'e', 'u', 'i' );

### Problem 6:  Weather Observation Station 10

Query the list of CITY names from **STATION** that do not end with vowels. Your result cannot contain duplicates.

#### Input format

The **STATION** table is described as follows:

| Field | Type |
|:----:|:----:|
| ID | NUMBER |
| CITY | VARCHAR2(21) |
| STATE | VARCHAR2(2)|
| LAT_N | NUMBER |
| LONG_W | NUMBER |

where LAT_N is the northern latitude and LONG_W is the western longitude.

In [0]:
# Solution
# SELECT distinct CITY FROM STATION WHERE RIGHT(CITY,1) not in ('a', 'o', 'e', 'u', 'i' );

### Problem 7:  Weather Observation Station 11

Query the list of CITY names from **STATION** that do not end with vowels or do not end with vowels. Your result cannot contain duplicates.

#### Input format

The **STATION** table is described as follows:

| Field | Type |
|:----:|:----:|
| ID | NUMBER |
| CITY | VARCHAR2(21) |
| STATE | VARCHAR2(2)|
| LAT_N | NUMBER |
| LONG_W | NUMBER |

where LAT_N is the northern latitude and LONG_W is the western longitude.

In [0]:
# Solution
# SELECT distinct CITY FROM STATION WHERE LEFT(CITY,1) not in ('a', 'o', 'e', 'u', 'i' ) OR RIGHT(CITY,1) not in ('a', 'o', 'e', 'u', 'i' );

### Problem 8:  Weather Observation Station 12

Query the list of CITY names from **STATION** that do not end with vowels and do not end with vowels. Your result cannot contain duplicates.

#### Input format

The **STATION** table is described as follows:

| Field | Type |
|:----:|:----:|
| ID | NUMBER |
| CITY | VARCHAR2(21) |
| STATE | VARCHAR2(2)|
| LAT_N | NUMBER |
| LONG_W | NUMBER |

where LAT_N is the northern latitude and LONG_W is the western longitude.

In [0]:
# Solution
# SELECT distinct CITY FROM STATION WHERE LEFT(CITY,1) not in ('a', 'o', 'e', 'u', 'i' ) AND RIGHT(CITY,1) not in ('a', 'o', 'e', 'u', 'i' );

### Problem 9: Revising Aggregations - The Count Function

Query a count of the number of cities in CITY having a Population larger than $100,000$.

#### Input format:
The **CITY** table is described as follows: 

| Field | Type |
|:----:|:---:|
| ID | NUMBER |
| NAME | VARCHAR2(17) |
| COUNTRYCODE | VARCHAR2(3) |
| DISTRICT | VARCHAR2(20) |
| POPULATION | NUMBER |

In [0]:
# Solution
# SELECT count(ID) FROM CITY WHERE POPULATION > 100000;

### Problem 10: Revising Aggregations - The Sum Function

Query the total population of all cities in **CITY** where District is **California**.

#### Input format:
The **CITY** table is described as follows: 

| Field | Type |
|:----:|:---:|
| ID | NUMBER |
| NAME | VARCHAR2(17) |
| COUNTRYCODE | VARCHAR2(3) |
| DISTRICT | VARCHAR2(20) |
| POPULATION | NUMBER |

In [0]:
# Solution
# SELECT sum(POPULATION) FROM CITY WHERE DISTRICT = 'California';